// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bind(arg1) {
  return window['go']['main']['App']['Bind'](arg1);
}

export function DevTool() {
  return window['go']['main']['App']['DevTool']();
}

export function On(arg1, arg2) {
  return window['go']['main']['App']['On'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function Resize(arg1) {
  return window['go']['main']['App']['Resize'](arg1);
}

export function Run() {
  return window['go']['main']['App']['Run']();
}

export function SetApplicationMenu(arg1) {
  return window['go']['main']['App']['SetApplicationMenu'](arg1);
}

export function Theme(arg1) {
  return window['go']['main']['App']['Theme'](arg1);
}
