// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {menu} from '../models';

export function Bind(arg1:any):Promise<void>;

export function DevTool():Promise<void>;

export function On(arg1:application.EventType,arg2:any):Promise<void>;

export function Quit():Promise<void>;

export function Refresh():Promise<void>;

export function Resize(arg1:boolean):Promise<void>;

export function Run():Promise<void>;

export function SetApplicationMenu(arg1:menu.Menu):Promise<void>;

export function Theme(arg1:boolean):Promise<void>;
